package com.appdirect.integration.models.events;

public enum EventType {
    SUBSCRIPTION_ORDER, SUBSCRIPTION_CHANGE, SUBSCRIPTION_CANCEL,SUBSCRIPTION_NOTICE,
    USER_ASSIGNMENT, USER_UNASSIGNMENT
}
